version: 2
jobs:
  test-minimal: &test-minimal
    docker:
      - image: circleci/python:3.6

    environment:
      OPTIONAL_MODULES: ""

    steps:
      - checkout

      - run:
          name: Add optional modules to requirements.txt
          command: |
            echo "$OPTIONAL_MODULES" >> requirements.txt

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover

  test-python-3-7:
    <<: *test-minimal

    docker:
      - image: circleci/python:3.7

  test-python-3-8:
    <<: *test-minimal

    docker:
      - image: circleci/python:3.8-rc

  test-py-bson:
    <<: *test-minimal

    environment:
      OPTIONAL_MODULES: bson

  test-pymongo-bson:
    <<: *test-minimal

    environment:
      OPTIONAL_MODULES: pymongo

workflows:
  version: 2
  build:
    jobs:
      - test-minimal
      - test-python-3-7
      - test-python-3-8
      - test-py-bson
      - test-pymongo-bson
